ITEM.name = "Mobile Med Kit"
ITEM.desc = "A portalable medkit."
ITEM.model = "models/weapons/w_medkit.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.class = "weapon_medkit"
ITEM.permit = "doc"
ITEM.category = "Medical Equipment"
ITEM.uniqueID = "weapon_medkit"
ITEM.noBusiness = true
ITEM.price = 500