ITEM.name = "Thermal Slam"
ITEM.desc = "A medium-sized explosive that can be planted on a wall or thrown."
ITEM.model = "models/weapons/w_slam.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 800
ITEM.noBusiness = true
ITEM.class = "weapon_slam"
ITEM.weaponCategory = "grenade"