ITEM.name = "A280C"
ITEM.class = "weapon_752bf3_a280"
ITEM.model = "models/weapons/synbf3/w_a280.mdl"
ITEM.desc = "Star Wars! PEW PEW PEW PEW"
ITEM.holsterDrawInfo = {}
ITEM.weaponCategory = "primary"
ITEM.uniqueID = "a280"
ITEM.width = 3
ITEM.height = 1
ITEM.noBusiness = true
ITEM.category = "Weapons"